version: '3.9'

services:
  opencr-postgres-1:
    environment:
      REPMGR_PARTNER_NODES: ${OPENCR_REPMGR_PARTNER_NODES}
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  opencr-postgres-2:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${OPENCR_HF_POSTGRESQL_PASSWORD}
      POSTGRESQL_USERNAME: ${OPENCR_HF_POSTGRESQL_USERNAME}
      POSTGRESQL_DATABASE: ${OPENCR_HF_POSTGRESQL_DATABASE}
      REPMGR_NODE_NETWORK_NAME: postgres-2
      REPMGR_PASSWORD: ${OPENCR_REPMGR_PASSWORD}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-2
      REPMGR_PRIMARY_HOST: ${OPENCR_REPMGR_PRIMARY_HOST}
      REPMGR_PARTNER_NODES: ${OPENCR_REPMGR_PARTNER_NODES}
    volumes:
      - 'hapi-postgres-2-data:/bitnami/postgresql'
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"
      replicas: 1
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT}
          memory: ${HF_POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE}
          memory: ${HF_POSTGRES_MEMORY_RESERVE}
    networks:
      default:
      opencr-postgres:
      pg_backup_net: {}


  opencr-postgres-3:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${OPENCR_HF_POSTGRESQL_PASSWORD}
      POSTGRESQL_USERNAME: ${OPENCR_HF_POSTGRESQL_USERNAME}
      POSTGRESQL_DATABASE: ${OPENCR_HF_POSTGRESQL_DATABASE}
      REPMGR_NODE_NETWORK_NAME: postgres-3
      REPMGR_PASSWORD: ${REPMGR_PASSWORD}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-3
      REPMGR_PRIMARY_HOST: ${OPENCR_REPMGR_PRIMARY_HOST}
      REPMGR_PARTNER_NODES: ${OPENCR_REPMGR_PARTNER_NODES}
    volumes:
      - 'hapi-postgres-3-data:/bitnami/postgresql'
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"
      replicas: 1
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT}
          memory: ${HF_POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE}
          memory: ${HF_POSTGRES_MEMORY_RESERVE}
    networks:
      default:
      opencr-postgres:
      pg_backup_net: {}


volumes:
  opencr-postgres-2-data:
  opencr-postgres-3-data:
