version: '3.9'

services:
  # docker-compose -f client-registry-opencr/docker-compose.yml --env-file client-registry-opencr/.env.build build
  opencr:
    image: itechuw/opencr:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${OPENCR_NODE_ENV:-docker}
      - HAPI_FHIR_URL=${OPENCR_HAPI_URL-http://opencr-hapi-fhir:8080/fhir/metadata}
    configs:
      - target: /src/server/config/config_ro.json
        source: config.json
      - target: /src/server/config/mediator.json
        source: mediator.json
      - target: /src/server/config/decisionRules.json
        source: decisionRules.json
      - target: /src/resources/Relationships/PatientRelationship.json
        source: PatientRelationship.json
    networks:
      - reverse-proxy
      - keycloak
      - opencr
      - default
      - openhim
      - traefik
    deploy:
      replicas: 1    
      restart_policy:
        condition: any
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik-public'
        - 'traefik.http.routers.opencr.tls=true'
        - 'traefik.http.routers.opencr.entrypoints=web-secure'
        - 'traefik.http.services.opencr.loadbalancer.server.port=3000'
        - 'traefik.http.routers.opencr.rule=Host(`hie-pilot.gov.bw`) && PathPrefix(`/crux`) || PathPrefix(`/ocrux`)'
        - 'traefik.http.services.opencr.loadbalancer.server.scheme=http'
        - 'traefik.http.routers.opencr.service=opencr'
    healthcheck:
      test: /usr/bin/wget --no-verbose --tries=1 --spider http://localhost:3000/crux/
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 1m
configs:
  config.json:
    file: ./config/_config.json
    name: config.json-${config_json_DIGEST:?err}
    labels:
      name: opencr
  mediator.json:
    file: ./config/mediator.json
    name: mediator.json-${mediator_json_DIGEST:?err}
    labels:
      name: opencr
  decisionRules.json:
    file: ./config/decisionRules.json
    name: decisionRules.json-${decisionRules_json_DIGEST:?err}
    labels:
      name: opencr
  PatientRelationship.json:
    file: ./config/PatientRelationship.json
    name: PatientRelationship.json-${PatientRelationship_json_DIGEST:?err}
    labels:
      name: opencr

networks:
  reverse-proxy:
    name: reverse-proxy_public
    external: true
  keycloak:
    name: keycloak_public
    external: true
  opencr:
    name: opencr
    external: true
  default:
  traefik:
    name: traefik-public
    external: true
  openhim:    
    name: openhim_public
    external: true
  omang:
    name: omang_public
    external: true