version: "3.9"

services:
  opencr-postgres-1:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${OPENCR_HF_POSTGRESQL_PASSWORD}
      POSTGRESQL_USERNAME: ${OPENCR_HF_POSTGRESQL_USERNAME}
      POSTGRESQL_DATABASE: ${OPENCR_HF_POSTGRESQL_DATABASE}
      REPMGR_NODE_NETWORK_NAME: opencr-postgres-1
      REPMGR_PASSWORD: ${CR_REPMGR_PASSWORD}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: opencr-postgres-1
      REPMGR_PRIMARY_HOST: ${CR_REPMGR_PRIMARY_HOST}
      REPMGR_PARTNER_NODES: ${CR_REPMGR_PARTNER_NODES}
      POSTGRESQL_POSTGRES_PASSWORD: ${OPENCR_HAPI_POSTGRES_PASSWORD}
    volumes:
      - "opencr-postgres-1-data:/bitnami/postgresql"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${OPENCR_HF_POSTGRES_CPU_LIMIT}
          memory: ${OPENCR_HF_POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${OPENCR_HF_POSTGRES_CPU_RESERVE}
          memory: ${OPENCR_HF_POSTGRES_MEMORY_RESERVE}
    networks:
      default:
      opencr:


volumes:
  opencr-postgres-1-data:

networks:
  default:
  opencr:
    name: opencr
    external: true

