version: "3.9"

services:

  opencr-hapi-fhir:
    build:
      context: ./
      dockerfile: hapi.Dockerfile
    image: itechuw/hapi-wget:v5.1.0
    networks:
      opencr:
      default:
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx2g
      - CATALINA_OPTS=-Xmx2g
    deploy:
      replicas: ${HAPI_FHIR_INSTANCES-1}
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: ${HAPI_FHIR_CPU_LIMIT-1}
          memory: ${HAPI_FHIR_MEMORY_LIMIT-2G}
        reservations:
          cpus: ${HAPI_FHIR_CPU_RESERVE-0.5}
          memory: ${HAPI_FHIR_MEMORY_RESERVE-1G}
    healthcheck:
      test: /bin/wget --no-verbose --tries=1 --spider http://localhost:8080
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 2m

networks:  
  default:
  opencr:
    name: opencr
    external: true