version: '3.8'

## Port Assignments:
##  See .env file

## Container debugging:
# 1. append the following lines to desired container
# 2. boot up the container using `docker-compose up -d`
# 3 run `docker exec -it <container-name> bash` to start interactive shell
#
#    tty: true
#    stdin_open: true
#    entrypoint: bash

services:
  hie-botswana:
    image: itechuw/hie-botswana:${VERSION-local}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.hie

