version: '2.4'

## Port Assignments:
##  See .env file

## Container debugging: 
# 1. append the following lines to desired container 
# 2. boot up the container using `docker-compose up -d`
# 3 run `docker exec -it <container-name> bash` to start interactive shell
# 
#    tty: true
#    stdin_open: true
#    entrypoint: bash

## Utility for booting up placeholder page:
# `docker run --hostname openhim-placeholder --network shared-health-record_sedish --name openhim-placeholder -e MESSAGE=OPENHIM-PLACEHOLDER -e PORT=3000 -d docker.io/sroze/landing-page:latest`

services:
  # static:
  #   image: docker.io/sroze/landing-page:latest
  #   container_name: homepage
  #   hostname: homepage
  #   environment: 
  #     - MESSAGE=HIE-BOTSWANA
  #   networks: 
  #     - hie
  #   ports:
  #     - 8082:80

  ###
  # nginx reverse proxy
  # TODO: set up to use non-root user. See https://www.rockyourcode.com/run-docker-nginx-as-non-root-user/
  # TODO: Run letsencrypt as docker container: https://hub.docker.com/r/certbot/certbot/
  ###
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/local/letsencrypt/archive/moh.org.bw:/etc/letsencrypt
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-data:/var/www
    networks:
      - hie
    
  ###
  # OpenCR
  ###
  opencr:
    container_name: opencr
    hostname: opencr
    image: intrahealth/opencr:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=docker
      - HAPI_FHIR_URL=http://opencr-fhir:8080/fhir/metadata
    networks:
      - hie
    volumes:
      - ./configs/opencr/config_docker.json:/src/server/config/config_docker.json
      - ./configs/opencr/mediator.json:/src/server/config/mediator.json
      # - ./configs/opencr/app.js:/src/server/lib/app.js
      - /home/ubuntu/local/letsencrypt/archive/moh.org.bw/privkey1.pem:/src/server/serverCertificates/server_key.pem
      - /home/ubuntu/local/letsencrypt/archive/moh.org.bw/fullchain1.pem:/src/server/serverCertificates/server_cert.pem   

  opencr-fhir:
    image: hapiproject/hapi:latest
    container_name: opencr-fhir
    hostname: opencr-fhir
    restart: unless-stopped
    ports:
      - "${CR_FHIR_PORT}:8080"
    networks:
      - hie
    healthcheck:
      test: "curl -sS http://opencr-fhir:8080/fhir/metadata || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - cr-data:/data/hapi
  opencr-es:
    container_name: es
    image: intrahealth/elasticsearch:latest
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    ports:
      - "${CR_ES_PORT}:9200"
    networks:
      - hie

  ###
  # SHR
  ###
  shr:
    container_name: shr
    hostname: shr
    image: ghcr.io/i-tech-uw/shared-health-record:pr-2
    ports:
      - "${SHR_PORT}:3000"
    restart: on-failure
    environment:
      - NODE_ENV=docker
    networks:
      - hie
    volumes:
      - ./configs/shr/config_docker_template.json:/server/config/config_docker.json
      - ./configs/shr/mediator.json:/server/config/mediator_docker.json
  shr-fhir:
    image: hapiproject/hapi:latest
    container_name: shr-fhir
    hostname: shr-fhir
    restart: unless-stopped
    volumes:
      - shr-data:/data/hapi
    networks:
      - hie
    healthcheck:
      test: "curl -sS http://shr-fhir:8080/fhir/metadata || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3


  ###
  # OpenHIM
  ###
  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim"
      mongo_atnaUrl: "mongodb://mongo-db/openhim"
      NODE_ENV: "development"
    ports:
      - 8080:8080
      - "5000:5000"
      - "5001:5001"
      # - "5050:5050"
      # - "5051:5051"
      # - "5052:5052"
      # - "7788:7788"
    healthcheck:
      test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - hie
      
  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    volumes:
      - ./configs/openhim-console/default.json:/usr/share/nginx/html/config/default.json
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - hie
  mongo-db:
    container_name: mongo-db
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped
    networks:
      - hie
  # pimsdb:
  #   container_name: pims_db
  #   image: mcr.microsoft.com/mssql/server:2017-latest
  #   environment:
  #     MSSQL_SA_PASSWORD: "Pimsdbpw12!"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - 1433:1433
  #   volumes:
  #     - ./db:/var/opt/mssql/backup
  #     - sqldata:/var/opt/mssql
      
volumes:
  es:
    driver: local
  mongo-data:
    driver: local
  sqldata:
    driver: local
  shr-data:
    driver: local
  cr-data:
    driver: local
  nginx-data:
    driver: local
networks:
  hie:
