version: '2.4'

## Port Assignments:
##  See .env file

## Container debugging: 
# 1. append the following lines to desired container 
# 2. boot up the container using `docker-compose up -d`
# 3 run `docker exec -it <container-name> bash` to start interactive shell
# 
#    tty: true
#    stdin_open: true
#    entrypoint: bash

services:
  ###
  # nginx reverse proxy
  # TODO: set up to use non-root user. See https://www.rockyourcode.com/run-docker-nginx-as-non-root-user/
  # TODO: Run letsencrypt as docker container: https://hub.docker.com/r/certbot/certbot/
  ###
  nginx:
    profiles: ["core"]
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
      - "5001:5001"
      - "5000:5000"
    volumes:
     # - /home/ubuntu/local/letsencrypt/archive/moh.org.bw:/etc/letsencrypt
      - ./configs/nginx/nginx.ports.conf:/etc/nginx/nginx.conf
      - nginx-data:/var/www
    networks:
      - hie
    logging:
      options:
        max-size: "10k"
        max-file: "3"
  ###
  # OpenCR
  ###
  opencr:
    profiles: ["mediator"]
    container_name: opencr
    hostname: opencr
    image: intrahealth/opencr:latest
    restart: unless-stopped
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=docker
      - HAPI_FHIR_URL=http://opencr-fhir:8080/fhir/metadata
    networks:
      - hie
    volumes:
      - ./configs/opencr/config_port.json:/src/server/config/config_docker.json
      - ./configs/opencr/mediator_port.json:/src/server/config/mediator.json
      # - /home/ubuntu/local/letsencrypt/archive/moh.org.bw/privkey1.pem:/src/server/serverCertificates/server_key.pem
      # - /home/ubuntu/local/letsencrypt/archive/moh.org.bw/fullchain1.pem:/src/server/serverCertificates/server_cert.pem   

  opencr-fhir:
    profiles: ["core"]
    image: hapiproject/hapi:latest
    container_name: opencr-fhir
    hostname: opencr-fhir
    restart: unless-stopped
    ports:
      - 8082:8080
    networks:
      - hie
    healthcheck:
      test: "curl -sS http://opencr-fhir:8080/fhir/metadata || exit 1"
      interval: 90s
      timeout: 30s
      retries: 3
    volumes:
      - cr-data:/data/hapi

  opencr-es:
    profiles: ["core"]
    container_name: es
    image: intrahealth/elasticsearch:latest
    restart: unless-stopped
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    networks:
      - hie

  ###
  # SHR
  ###
  shr:
    profiles: ["mediator"]
    container_name: shr
    hostname: shr
    image: ghcr.io/i-tech-uw/shared-health-record:v0.2.0
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=docker
    networks:
      - hie
    volumes:
      - ./configs/shr/config_docker_template.json:/app/config/config_docker.json
      - ./configs/shr/mediator.json:/app/config/mediator_docker.json

  shr-fhir:
    profiles: ["core"]
    image: hapiproject/hapi:latest
    container_name: shr-fhir
    hostname: shr-fhir
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - shr-data:/data/hapi
    networks:
      - hie
    healthcheck:
      test: "curl -sS http://shr-fhir:8080/fhir/metadata || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

  ###
  # OpenHIM
  ###
  openhim-core:
    profiles: ["core"]
    container_name: openhim-core
    hostname: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim"
      mongo_atnaUrl: "mongodb://mongo-db/openhim"
      NODE_ENV: "development"
    healthcheck:
      test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - hie
    extra_hosts:
      - "host.docker.internal:172.22.16.1"
    # ports:
      # - 8080:8080
      # - "5000:5000"
      # - "5001:5001"
      # - "5050:5050"
      # - "5051:5051"
      # - "5052:5052"
      # - "7788:7788"
  openhim-console:
    profiles: ["core"]
    container_name: openhim-console
    hostname: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    # ports:
    #   - 80:80
    volumes:
      - ./configs/openhim-console/port.json:/usr/share/nginx/html/config/default.json
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - hie
  mongo-db:
    profiles: ["core"]
    container_name: mongo-db
    image: mongo:3.4
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped
    networks:
      - hie

  fhir-converter:
    profiles: ["mediator"]
    container_name: fhir-converter
    hostname: fhir-converter
    restart: unless-stopped
    ports:
      - 2019:2019
    image: ghcr.io/b-techbw/openhim-mediator-fhir-converter:latest
    volumes:
      - ./configs/fhir-converter/config_port.json:/app/config.json
      - /app/src/service-templates
    networks:
      - hie
  
  mllp-adapter:
    profiles: ["mediator"]
    image: rivethealth/mllp-http
    hostname: mllp
    container_name: mllp
    ports:
    - 2575:2575
    command:
      - "mllp2http"
      - "--log-level=info"
      - "--content-type=text/plain"
      - "http://openhim-core:5001/mllp/"
    networks:
    - hie
  
  httpbin:
    profiles: ["test"]
    image: kennethreitz/httpbin
    container_name: httpbin
    hostname: httpbin
    networks:
    - hie
  
  # Newman Tests
  newman:
    profiles: ["test"]
    image: postman/newman
    volumes:
      - ./.postman:/.postman
    entrypoint: newman run $POSTMAN_COLLECTION -e /.postman/postman_env.ci.json --insecure --timeout-request 20000 --delay-request 500
    networks:
      - hie

  mllp_tests:
    profiles: ["test"]
    container_name: mllp_tests
    build: ./test
    networks:
      - hie
    volumes:
      - ./test:/test
volumes:
  es:
    driver: local
  mongo-data:
    driver: local
  sqldata:
    driver: local
  shr-data:
    driver: local
  cr-data:
    driver: local
  nginx-data:
    driver: local
networks:
  hie:
