version: '3.8'
services:
  # Newman Tests
  newman:
    profiles: ["test"]
    image: postman/newman
    volumes:
      - ./.postman:/.postman
    entrypoint: newman run $POSTMAN_COLLECTION -e /.postman/postman_env.ci.json --insecure --timeout-request 20000 --delay-request 500
    networks:
      - hie

  mllp_tests:
    profiles: ["test"]
    container_name: mllp_tests
    image: ghcr.io/b-techbw/mllp-tester:latest
    networks:
      - hie

networks:
  hie:
    external: true
    