version: '2.4'

## Port Assignments:
##  See .env file

## Container debugging: 
# 1. append the following lines to desired container 
# 2. boot up the container using `docker-compose up -d`
# 3 run `docker exec -it <container-name> bash` to start interactive shell
# 
#    tty: true
#    stdin_open: true
#    entrypoint: bash

services:
  ###
  # nginx reverse proxy
  # TODO: set up to use non-root user. See https://www.rockyourcode.com/run-docker-nginx-as-non-root-user/
  # TODO: Run letsencrypt as docker container: https://hub.docker.com/r/certbot/certbot/
  ###
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 8090:8090
      - 5000:5000
      - 5001:5001
      - 2575:2575
    volumes:
      - ./configs/nginx/nginx.local.conf:/etc/nginx/nginx.conf
      - nginx-data:/var/www
      - ./configs/nginx/certs:/etc/certs
    networks:
      - hie
    logging:
      options:
        max-size: "10k"
        max-file: "3"

  ###
  # OpenCR
  ###
  opencr:
    container_name: opencr
    hostname: opencr
    image: intrahealth/opencr:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=docker
      - HAPI_FHIR_URL=http://opencr-fhir:8080/fhir/metadata
    networks:
      - hie
    volumes:
      - ./configs/opencr/config_port.json:/src/server/config/config_docker.json
      - ./configs/opencr/mediator_port.json:/src/server/config/mediator.json

  opencr-fhir:
    image: hapiproject/hapi:latest
    container_name: opencr-fhir
    hostname: opencr-fhir
    restart: unless-stopped
    networks:
      - hie
    healthcheck:
      test: "curl -sS http://opencr-fhir:8080/fhir/metadata || exit 1"
      interval: 90s
      timeout: 30s
      retries: 3
    volumes:
      - cr-data:/data/hapi

  opencr-es:
    container_name: es
    image: intrahealth/elasticsearch:latest
    restart: unless-stopped
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    networks:
      - hie

  ###
  # SHR
  ###
  shr:
    container_name: shr
    hostname: shr
    image: ghcr.io/i-tech-uw/shared-health-record:v0.3.3
    restart: unless-stopped
    environment:
      - NODE_ENV=docker
    networks:
      - hie
    volumes:
      - ./configs/shr/config_ports.json:/app/config/config_docker.json
      - ./configs/shr/mediator_ports.json:/app/config/mediator_docker.json

  shr-fhir:
    image: hapiproject/hapi:latest
    container_name: shr-fhir
    hostname: shr-fhir
    restart: unless-stopped
    volumes:
      - shr-data:/data/hapi
    networks:
      - hie
    healthcheck:
      test: "curl -sS http://shr-fhir:8080/fhir/metadata || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3

  ###
  # OpenHIM
  ###
  openhim-core:
    container_name: openhim-core
    hostname: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim"
      mongo_atnaUrl: "mongodb://mongo-db/openhim"
      NODE_ENV: "development"
    healthcheck:
      test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - hie

  openhim-console:
    container_name: openhim-console
    hostname: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    volumes:
      - ./configs/openhim-console/port.json:/usr/share/nginx/html/config/default.json
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - hie

  mongo-db:
    container_name: mongo-db
    image: mongo:3.4
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped
    networks:
      - hie

  fhir-converter:
    container_name: fhir-converter
    hostname: fhir-converter
    restart: unless-stopped
    image: ghcr.io/b-techbw/openhim-mediator-fhir-converter:latest
    volumes:
      - ./configs/fhir-converter/config_port.json:/app/config.json
      - /app/src/service-templates
    networks:
      - hie

  httpbin:
    image: kennethreitz/httpbin:latest
    container_name: httpbin
    hostname: httpbin
    networks:
    - hie
  
  # Newman Tests
  newman:
    image: postman/newman
    volumes:
      - ./.postman:/.postman
    entrypoint: newman run $POSTMAN_COLLECTION -e /.postman/postman_env.ci.json --insecure --timeout-request 20000 --delay-request 500
    networks:
      - hie

  mllp_tests:
    container_name: mllp_tests
    image: ghcr.io/b-techbw/mllp-tester:main
    networks:
      - hie
    volumes:
      - ./test/mllp:/test
    tty: true
    stdin_open: true
    entrypoint: sh

volumes:
  es:
    driver: local
  mongo-data:
    driver: local
  sqldata:
    driver: local
  shr-data:
    driver: local
  cr-data:
    driver: local
  nginx-data:
    driver: local
networks:
  hie:
