version: '3.9'

services:
  openhim-mediator-fhir-converter:
    ports:
      - target: 9229
        published: 9229
        mode: host
      - target: 2019
        published: 2019
        mode: host
    entrypoint: /app/deploy/debug.sh
