# config file version
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
- name: LokiLogs
  type: loki
  access: direct
  url: http://loki:3100
