log:
  level: DEBUG
serversTransport:
  insecureSkipVerify: true
entryPoints:
  web:
    address: ":80"
  web-secure:
    address: :443
api:
  dashboard: true
  insecure: false
providers:
  file:
    watch: true
    directory: /etc/traefik/dynamic_conf
  docker:
    exposedByDefault: false
