log:
  level: INFO
serversTransport:
  insecureSkipVerify: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: web-secure
          scheme: https
  web-secure:
    address: :443
api:
  insecure: true
providers:
  docker:
    exposedByDefault: false
