version: '3.9'

services:
  grafana:
    ports:
      - target: 3000
        published: 3000
        mode: host

  prometheus:
    ports:
      - target: 9090
        published: 9090
        mode: host

  loki:
    ports:
      - target: 3100
        published: 3100
        mode: host

  minio-01:
    ports:
      - target: 9001
        published: 9005
        mode: host
