version: '3.9'

services:
  openhim-core:
    image: jembi/openhim-core:v8.0.1
    container_name: openhim-core
    networks:
      kafka:
      hapi-fhir:
      reverse-proxy:
      keycloak:
      public:
      default:
      opencr:
    environment:
      - mongo_url=${OPENHIM_MONGO_URL}
      - mongo_atnaUrl=${OPENHIM_MONGO_ATNAURL}
      - api_authenticationTypes=["token", "basic", "openid", "local"]
      - authentication_enableCustomTokenAuthentication=true
      - router_kafkaBrokers=${KAFKA_HOSTS}
      - api_openid_url=${KC_FRONTEND_URL}/realms/${KC_REALM_NAME}
      - api_openid_callbackUrl=${KC_OPENHIM_ROOT_URL}
      - api_openid_clientId=${KC_OPENHIM_CLIENT_ID}
      - api_openid_clientSecret=${KC_OPENHIM_CLIENT_SECRET}
    deploy:
      replicas: ${OPENHIM_CORE_INSTANCES}
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: ${OPENHIM_CPU_LIMIT}
          memory: ${OPENHIM_MEMORY_LIMIT}
        reservations:
          cpus: ${OPENHIM_CPU_RESERVE}
          memory: ${OPENHIM_MEMORY_RESERVE}

  openhim-console:
    image: jembi/openhim-console:v1.18.2
    environment:
      OPENHIM_CORE_MEDIATOR_HOSTNAME: ${OPENHIM_CORE_MEDIATOR_HOSTNAME}
      OPENHIM_MEDIATOR_API_PORT: ${OPENHIM_MEDIATOR_API_PORT}
      KC_OPENHIM_SSO_ENABLED: ${KC_OPENHIM_SSO_ENABLED}
      KC_OPENHIM_CLIENT_ID: ${KC_OPENHIM_CLIENT_ID}
      KC_REALM_NAME: ${KC_REALM_NAME}
      KC_FRONTEND_URL: ${KC_FRONTEND_URL}
    networks:
      reverse-proxy:
      keycloak:
      public:
      default:
    deploy:
      replicas: ${OPENHIM_CONSOLE_INSTANCES}
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: ${OPENHIM_CONSOLE_CPU_LIMIT}
          memory: ${OPENHIM_CONSOLE_MEMORY_LIMIT}
        reservations:
          cpus: ${OPENHIM_CONSOLE_CPU_RESERVE}
          memory: ${OPENHIM_CONSOLE_MEMORY_RESERVE}

networks:
  kafka:
    name: kafka_public
    external: true
  hapi-fhir:
    name: hapi-fhir_public
    external: true
  reverse-proxy:
    name: reverse-proxy_public
    external: true
  keycloak:
    name: keycloak_public
    external: true
  opencr:
    name: opencr
    external: true
  public:
    name: openhim_public
    external: true
  default:
