---
- name: Preparation
  hosts: all
  remote_user: "{{ user }}"
  become: true
  tags: prep

  vars_prompt:
    - name: "user"
      prompt: "Please enter the username (with sudo)"
      private: no

    - name: "pgpass"
      prompt: "Please provide the password for the hapi postgres user in plain text (it will be md5-hashed)"
      private: no

  tasks:

  # postgres

    - name: install the postgres pgdg from remote
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present

    - name: install postgres components
      yum:
        name: 
          - postgresql10 
          - postgresql10-server 
          - postgresql10-contrib 
          - postgresql10-libs
        state: latest



    # - stat:
    #     path: /var/lib/pgsql/10/data
    #   register: pgdata 


# postgres initdb: this should fail if it exists - and that's okay 

    - name: Initialize Postgres
      command: /usr/pgsql-10/bin/postgresql-10-setup initdb
      # when: pgdata.stat.exists == False
      ignore_errors: yes 


# note that postgres initdb installs its own systemd unit

    - name: run pg
      service: 
        name: postgresql-10
        state: started
        enabled: yes
        # daemon_reload: yes


    - name: Create a new database with name hapi
      postgresql_db:
        name: hapi
      become_user: postgres


# create hapi user

    - name: Connect to hapi database, create hapi user, and grant access
      postgresql_user:
        db: hapi
        name: hapi
        password: "{{ pgpass }}"
        encrypted: yes
        priv: ALL
      become_user: postgres

    - name: Confirm actions worked for hapi database/user
      become: yes
      become_user: postgres
      postgresql_info:
        db: hapi
        filter: "!settings"
      register: pginfo

    - debug:
        msg: "{{ pginfo }}"


# todo: check if these entries can be removed
# authorize ident or it wont work
# see: https://serverfault.com/questions/406606/postgres-error-message-fatal-ident-authentication-failed-for-user
# could be changed to md5 from trust?
# https://www.cyberciti.biz/faq/psql-fatal-ident-authentication-failed-for-user/

    - name: Comment out entries in pg_hba.conf
      replace:
        dest: /var/lib/pgsql/10/data/pg_hba.conf
        regexp: '^local   all'
        replace: '#local   all'

    - name: Comment out entries in pg_hba.conf
      replace:
        dest: /var/lib/pgsql/10/data/pg_hba.conf
        regexp: '^host    all'
        replace: '#host    all'


    - name: Add a line to a file
      lineinfile:
        path: /var/lib/pgsql/10/data/pg_hba.conf
        line: "local	all	all	trust"


    - name: Add a line to a file
      lineinfile:
        path: /var/lib/pgsql/10/data/pg_hba.conf
        line: "host all all 127.0.0.1/32 trust"


    - name: run pg
      service: 
        name: postgresql-10
        state: restarted
        enabled: yes
        # daemon_reload: yes
