version: '3.9'

services:
  message-bus-kafka-config-importer:
    image: jembi/instantohie-config-importer
    deploy:
      restart_policy:
        condition: none
    environment:
      KAFDROP_HOST: kafdrop
      KAFDROP_PORT: 9013
      KAFKA_TOPICS: ${KAFKA_TOPICS}
    command: sh -c "wait-on -t 60000 http-get://kafdrop:9013/topic && node /kafka.js && echo 'success';"
    configs:
      - source: kafka.js
        target: /kafka.js

configs:
  kafka.js:
    file: ./kafka.js
    name: kafka-config.js-${kafka_config_DIGEST:?err}
    labels:
      name: kafka
