-- ALTER SESSION SET CONTAINER = ORCLPDB1;
CREATE USER omang IDENTIFIED BY "some-password";

CREATE USER bdr IDENTIFIED BY "some-password";

-- ALTER SESSION SET CONTAINER = ORCLPDB1;
GRANT CONNECT TO omang;

GRANT CONNECT TO bdr;

GRANT CREATE SESSION TO omang;

GRANT CREATE SESSION TO bdr;

GRANT RESOURCE TO omang;

GRANT RESOURCE TO bdr;

ALTER USER omang QUOTA 100M ON USERS;

ALTER USER bdr QUOTA 100M ON USERS;

-- ALTER SESSION SET CONTAINER = ORCLPDB1;
-- ALTER SESSION SET CURRENT_SCHEMA = omang;
--Create table
CREATE TABLE omang.OMANG_CITIZEN(
	DECEASED_DTE timestamp NULL,
	FIRST_NME VARCHAR2(50) NOT NULL,
	BIRTH_DTE_UNKNOWN VARCHAR2(50) NOT NULL,
	DISTRICT_NME VARCHAR2(50) NOT NULL,
	OCCUPATION_DESCR VARCHAR2(50) NOT NULL,
	BIRTH_PLACE_NME VARCHAR2(50) NOT NULL,
	CHANGE_DTE timestamp NOT NULL,
	DISTRICT_CDE VARCHAR2(50) NOT NULL,
	SEX VARCHAR2(50) NOT NULL,
	SPOUSE_NME VARCHAR2(50) NULL,
	CITIZEN_STATUS_CDE VARCHAR2(50) NOT NULL,
	DEATH_CERT_NO VARCHAR2(50) NULL,
	BIRTH_DTE timestamp NOT NULL,
	DECEASED_DTE_UNKNOWN VARCHAR2(50) NULL,
	CITIZEN_STATUS_DTE timestamp NOT NULL,
	SURNME VARCHAR2(50) NOT NULL,
	OCCUPATION_CDE VARCHAR2(50) NOT NULL,
	MARITAL_STATUS_CDE VARCHAR2(50) NOT NULL,
	EXPIRY_DTE timestamp NOT NULL,
	PERSON_STATUS VARCHAR2(50) NOT NULL,
	MARITAL_STATUS_DESCR VARCHAR2(50) NOT NULL,
	ID_NO VARCHAR2(50) NOT NULL,
	POSTAL_ADDR VARCHAR2(200),
	RESIDENTIAL_ADDR VARCHAR2(200)
);

--Insert into table
INSERT INTO
	omang.OMANG_CITIZEN (
		DECEASED_DTE,
		FIRST_NME,
		BIRTH_DTE_UNKNOWN,
		DISTRICT_NME,
		OCCUPATION_DESCR,
		BIRTH_PLACE_NME,
		CHANGE_DTE,
		DISTRICT_CDE,
		SEX,
		SPOUSE_NME,
		CITIZEN_STATUS_CDE,
		DEATH_CERT_NO,
		BIRTH_DTE,
		DECEASED_DTE_UNKNOWN,
		CITIZEN_STATUS_DTE,
		SURNME,
		OCCUPATION_CDE,
		MARITAL_STATUS_CDE,
		EXPIRY_DTE,
		PERSON_STATUS,
		MARITAL_STATUS_DESCR,
		ID_NO
	)
VALUES
	(
		NULL,
		'OLEBILE',
		'False',
		'CENTRAL-TUTUME',
		'NOT IN THE LABOUR FORCE (STUDENT)',
		'FRANCISTOW',
		TO_TIMESTAMP('2009-06-18', 'YYYY-MM-DD'),
		'18',
		'M',
		NULL,
		'CITZ',
		NULL,
		TO_TIMESTAMP('1992-08-27', 'YYYY-MM-DD'),
		NULL,
		TO_TIMESTAMP('2009-06-18', 'YYYY-MM-DD'),
		'SURNAME3',
		'28',
		'SGL',
		TO_TIMESTAMP('2019-05-27', 'YYYY-MM-DD'),
		'LIVE',
		'Single',
		'210711926'
	);

CREATE TABLE bdr.V_BIRTH(
	BIRTH_CERTIFICATE VARCHAR2(50) NULL,
	BIRTH_CERTIFICATE_OLD VARCHAR2(50) NULL,
	DISTRICT_OF_BIRTH VARCHAR2(50) NULL,
	DISTRICT_OF_BIRTH_NAME VARCHAR2(50) NULL,
	TYPE_OF_BIRTH VARCHAR2(50) NULL,
	ID_NUMBER VARCHAR2(50) NOT NULL,
	REGISTRATION_NUMBER VARCHAR2(50) NULL,
	FORENAME VARCHAR2(50) NOT NULL,
	SURNAME VARCHAR2(50) NOT NULL,
	OTHER_NAME VARCHAR2(50) NULL,
	NATIONALITY VARCHAR2(50) NULL,
	DATE_OF_BIRTH timestamp NULL,
	SEX VARCHAR2(50) NOT NULL,
	TOWN_VILL VARCHAR2(200) NULL,
	WARD_STREET VARCHAR2(200) NULL,
	DATE_OF_REGISTRATION timestamp NULL,
	DISTRICT_OF_REGISTRATION VARCHAR2(50) NULL,
	FATHER_ID_NUMBER VARCHAR2(50) NULL,
	FATHER_FORENAME VARCHAR2(50) NULL,
	FATHER_SURNAME VARCHAR2(50) NULL,
	FATHER_OTHER_NAME VARCHAR2(50) NULL,
	FATHER_NATIONALITY VARCHAR2(50) NULL,
	MOTHER_ID_NUMBER VARCHAR2(50) NULL,
	MOTHER_FORENAME VARCHAR2(50) NULL,
	MOTHER_SURNAME VARCHAR2(50) NULL,
	MOTHER_OTHER_NAME VARCHAR2(50) NULL,
	MOTHER_NATIONALITY VARCHAR2(50) NULL,
	MOTHER_AGE VARCHAR2(50) NULL,
	MOTHER_MARITAL_STATUS VARCHAR2(50) NULL,
	DATE_OF_ISSUE timestamp NULL,
	DATE_OF_COLLECTION timestamp NULL,
	YEAR_OF_REGISTRATION VARCHAR2(50) NULL
);

INSERT INTO
	bdr.V_BIRTH (
		BIRTH_CERTIFICATE,
		BIRTH_CERTIFICATE_OLD,
		DISTRICT_OF_REGISTRATION,
		DISTRICT_OF_BIRTH_NAME,
		DISTRICT_OF_BIRTH,
		TYPE_OF_BIRTH,
		ID_NUMBER,
		REGISTRATION_NUMBER,
		FORENAME,
		SURNAME,
		OTHER_NAME,
		NATIONALITY,
		DATE_OF_BIRTH,
		SEX,
		TOWN_VILL,
		WARD_STREET,
		DATE_OF_REGISTRATION,
		FATHER_ID_NUMBER,
		FATHER_FORENAME,
		FATHER_SURNAME,
		FATHER_OTHER_NAME,
		FATHER_NATIONALITY,
		MOTHER_ID_NUMBER,
		MOTHER_FORENAME,
		MOTHER_SURNAME,
		MOTHER_OTHER_NAME,
		MOTHER_NATIONALITY,
		DATE_OF_ISSUE,
		YEAR_OF_REGISTRATION,
		DATE_OF_COLLECTION,
		MOTHER_AGE,
		MOTHER_MARITAL_STATUS
	)
VALUES
	(
		'654651651651',
		'65461651',
		'18',
		'CENTRAL-TUTUME',
		'18',
		NULL,
		'23423423422',
		'324239022390',
		'OLEBILE',
		'SURNAME3',
		NULL,
		'BW',
		TO_TIMESTAMP('1992-08-27', 'YYYY-MM-DD'),
		'M',
		'FRANCISTOW',
		NULL,
		TO_TIMESTAMP('2009-06-18', 'YYYY-MM-DD'),
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		TO_TIMESTAMP('2009-06-18', 'YYYY-MM-DD'),
		'2009',
		TO_TIMESTAMP('2019-05-27', 'YYYY-MM-DD'),
		'60',
		NULL
	);

CREATE TABLE bdr.V_DEATH(
	DEATH_CERTIFICATE VARCHAR2(50) NULL,
	DISTRICT_OF_REGISTRATION VARCHAR2(50) NULL,
	DISTRICT_OF_DEATH VARCHAR2(50) NULL,
	DISTRICT_OF_DEATH_NAME VARCHAR2(50) NULL,
	ID_NUMBER VARCHAR2(50) NOT NULL,
	REGISTRATION_NUMBER VARCHAR2(50) NULL,
	FORENAME VARCHAR2(50) NOT NULL,
	SURNAME VARCHAR2(50) NOT NULL,
	OTHER_NAME VARCHAR2(50) NULL,
	NATIONALITY VARCHAR2(50) NULL,
	OCCUPATION VARCHAR2(50) NULL,
	DATE_OF_DEATH timestamp NULL,
	SEX VARCHAR2(50) NOT NULL,
	TOWN_VILL VARCHAR2(200) NULL,
	WARD_STREET VARCHAR2(200) NULL,
	PLACE_OF_DEATH VARCHAR2(50) NULL,
	DATE_OF_REGISTRATION timestamp NULL,
	AGE_DAYS VARCHAR2(50) NULL,
	AGE_MONTHS VARCHAR2(50) NULL,
	AGE_YEARS VARCHAR2(50) NULL,
	CODE_ICD10 VARCHAR2(50) NULL,
	CAUSE_OF_DEATH VARCHAR2(50) NULL,
	DATE_OF_ISSUE timestamp NULL,
	YEAR_OF_REGISTRATION VARCHAR2(50) NULL,
	TYPE_OF_RELATIONSHIP VARCHAR2(50) NULL,
	ID_NUMBER_NEXT_OF_KIN VARCHAR2(50) NULL,
	MOTHER_NATIONALITY VARCHAR2(50) NULL,
	FORENAME_NEXT_OF_KIN VARCHAR2(50) NULL,
	SURNAME_NEXT_OF_KIN VARCHAR2(50) NULL,
	OTHER_NAME_NEXT_OF_KIN VARCHAR2(50) NULL,
	NATIONALITY_NEXT_OF_KIN VARCHAR2(50) NULL,
	DATE_OF_COLLECTION timestamp NULL
);

INSERT INTO
	bdr.V_DEATH (
		DEATH_CERTIFICATE,
		DISTRICT_OF_REGISTRATION,
		DISTRICT_OF_DEATH_NAME,
		DISTRICT_OF_DEATH,
		ID_NUMBER,
		REGISTRATION_NUMBER,
		FORENAME,
		SURNAME,
		OTHER_NAME,
		NATIONALITY,
		OCCUPATION,
		DATE_OF_DEATH,
		SEX,
		TOWN_VILL,
		WARD_STREET,
		PLACE_OF_DEATH,
		DATE_OF_REGISTRATION,
		AGE_DAYS,
		AGE_MONTHS,
		AGE_YEARS,
		CODE_ICD10,
		CAUSE_OF_DEATH,
		DATE_OF_ISSUE,
		YEAR_OF_REGISTRATION,
		TYPE_OF_RELATIONSHIP,
		ID_NUMBER_NEXT_OF_KIN,
		FORENAME_NEXT_OF_KIN,
		SURNAME_NEXT_OF_KIN,
		OTHER_NAME_NEXT_OF_KIN,
		NATIONALITY_NEXT_OF_KIN,
		DATE_OF_COLLECTION
	)
VALUES
	(
		'654651651651',
		'18',
		'CENTRAL-TUTUME',
		'18',
		'23423423422',
		'324239022390',
		'OLEBILE',
		'SURNAME3',
		NULL,
		'BW',
		'NOT IN THE LABOUR FORCE (STUDENT)',
		NULL,
		'M',
		'FRANCISTOW',
		NULL,
		NULL,
		TO_TIMESTAMP('2009-06-18', 'YYYY-MM-DD'),
		30,
		0,
		0,
		NULL,
		NULL,
		TO_TIMESTAMP('2019-05-27', 'YYYY-MM-DD'),
		'2009',
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL,
		TO_TIMESTAMP('2009-06-18', 'YYYY-MM-DD')
	);