-- ALTER SESSION SET CONTAINER = ORCLPDB1;

CREATE USER omang IDENTIFIED BY "some-password";

-- ALTER SESSION SET CONTAINER = ORCLPDB1;

GRANT CONNECT TO omang;
GRANT CREATE SESSION TO omang;
GRANT RESOURCE TO omang;

ALTER USER omang QUOTA 100M ON USERS;

-- ALTER SESSION SET CONTAINER = ORCLPDB1;
-- ALTER SESSION SET CURRENT_SCHEMA = omang;

USE OMANG

--Create table
CREATE TABLE omang.OMANG_CITIZEN(
	DECEASED_DTE timestamp NULL,
	FIRST_NME VARCHAR2(50) NOT NULL,
	BIRTH_DTE_UNKNOWN VARCHAR2(50) NOT NULL,
	DISTRICT_NME VARCHAR2(50) NOT NULL,
	OCCUPATION_DESCR VARCHAR2(50) NOT NULL,
	BIRTH_PLACE_NME VARCHAR2(50) NOT NULL,
	CHANGE_DTE timestamp NOT NULL,
	DISTRICT_CDE VARCHAR2(50) NOT NULL,
	SEX VARCHAR2(50) NOT NULL,
	SPOUSE_NME VARCHAR2(50) NULL,
	CITIZEN_STATUS_CDE VARCHAR2(50) NOT NULL,
	DEATH_CERT_NO VARCHAR2(50) NULL,
	BIRTH_DTE timestamp NOT NULL,
	DECEASED_DTE_UNKNOWN VARCHAR2(50) NULL,
	CITIZEN_STATUS_DTE timestamp NOT NULL,
	SURNME VARCHAR2(50) NOT NULL,
	OCCUPATION_CDE VARCHAR2(50) NOT NULL,
	MARITAL_STATUS_CDE VARCHAR2(50) NOT NULL,
	EXPIRY_DTE timestamp NOT NULL,
	PERSON_STATUS VARCHAR2(50) NOT NULL,
	MARITAL_STATUS_DESCR VARCHAR2(50) NOT NULL,
	ID_NO VARCHAR2(50) NOT NULL
)
--Insert into table

INSERT INTO omang.OMANG_CITIZEN (DECEASED_DTE, FIRST_NME, BIRTH_DTE_UNKNOWN, DISTRICT_NME, OCCUPATION_DESCR, BIRTH_PLACE_NME, CHANGE_DTE, DISTRICT_CDE, SEX, SPOUSE_NME, CITIZEN_STATUS_CDE, DEATH_CERT_NO, BIRTH_DTE, DECEASED_DTE_UNKNOWN, CITIZEN_STATUS_DTE, SURNME, OCCUPATION_CDE, MARITAL_STATUS_CDE, EXPIRY_DTE, PERSON_STATUS, MARITAL_STATUS_DESCR, ID_NO) VALUES (NULL, 'OLEBILE', '', 'CENTRAL-TUTUME', 'NOT IN THE LABOUR FORCE (STUDENT)', 'FRANCISTOW', TO_TIMESTAMP('2009-06-18', 'YYYY-MM-DD'), '18', 'M', NULL, 'CITZ', NULL, TO_TIMESTAMP('1992-08-27','YYYY-MM-DD'), NULL, TO_TIMESTAMP('2009-06-18','YYYY-MM-DD'), 'SURNAME3', '28', 'SGL', TO_TIMESTAMP('2019-05-27','YYYY-MM-DD'), 'LIVE', 'Single', '210711926');

-- INSERT omang.OMANG_CITIZEN (DECEASED_DTE, FIRST_NME, BIRTH_DTE_UNKNOWN, DISTRICT_NME, OCCUPATION_DESCR, BIRTH_PLACE_NME, CHANGE_DTE, DISTRICT_CDE, SEX, SPOUSE_NME, CITIZEN_STATUS_CDE, DEATH_CERT_NO, BIRTH_DTE, DECEASED_DTE_UNKNOWN, CITIZEN_STATUS_DTE, SURNME, OCCUPATION_CDE, MARITAL_STATUS_CDE, EXPIRY_DTE, PERSON_STATUS, MARITAL_STATUS_DESCR, ID_NO) VALUES (NULL, N'OLEBILE', N'N', N'CENTRAL-TUTUME', N'NOT IN THE LABOUR FORCE (STUDENT)', N'FRANCISTOWN', CAST(N'2009-06-18T09:00:32.000' AS DateTime), N'18', N'M', NULL, N'CITZ', NULL, CAST(N'1992-08-27T00:00:00.000' AS DateTime), NULL, CAST(N'2009-06-18T09:00:32.000' AS DateTime), N'SURNAME3', N'28', N'SGL', CAST(N'2019-05-27T00:00:00.000' AS DateTime), N'LIVE', N'Single', N'210711926')

-- INSERT omang.OMANG_CITIZEN (DECEASED_DTE, FIRST_NME, BIRTH_DTE_UNKNOWN, DISTRICT_NME, OCCUPATION_DESCR, BIRTH_PLACE_NME, CHANGE_DTE, DISTRICT_CDE, SEX, SPOUSE_NME, CITIZEN_STATUS_CDE, DEATH_CERT_NO, BIRTH_DTE, DECEASED_DTE_UNKNOWN, CITIZEN_STATUS_DTE, SURNME, OCCUPATION_CDE, MARITAL_STATUS_CDE, EXPIRY_DTE, PERSON_STATUS, MARITAL_STATUS_DESCR, ID_NO) VALUES (NULL, N'ARABANG', N'N', N'NORTH-EAST', N'NOT IN THE LABOUR FORCE (STUDENT)', N'FRANCISTOWN', CAST(N'2015-05-20T08:03:52.000' AS DateTime), N'19', N'M', NULL, N'CITZ', NULL, CAST(N'1999-05-02T00:00:00.000' AS DateTime), NULL, CAST(N'2015-05-20T08:03:52.000' AS DateTime), N'SURNAME1', N'28', N'SGL', CAST(N'2025-05-18T00:00:00.000' AS DateTime), N'LIVE', N'Single', N'237718130')

-- INSERT omang.OMANG_CITIZEN (DECEASED_DTE, FIRST_NME, BIRTH_DTE_UNKNOWN, DISTRICT_NME, OCCUPATION_DESCR, BIRTH_PLACE_NME, CHANGE_DTE, DISTRICT_CDE, SEX, SPOUSE_NME, CITIZEN_STATUS_CDE, DEATH_CERT_NO, BIRTH_DTE, DECEASED_DTE_UNKNOWN, CITIZEN_STATUS_DTE, SURNME, OCCUPATION_CDE, MARITAL_STATUS_CDE, EXPIRY_DTE, PERSON_STATUS, MARITAL_STATUS_DESCR, ID_NO) VALUES (NULL, N'EMMANUEL', N'N', N'CENTRAL-TUTUME', N'NOT IN THE LABOUR FORCE (STUDENT)', N'FRANCISTOWN', CAST(N'2011-01-25T10:05:15.000' AS DateTime), N'18', N'M', NULL, N'CITZ', NULL, CAST(N'1994-11-30T00:00:00.000' AS DateTime), NULL, CAST(N'2011-01-25T10:05:15.000' AS DateTime), N'SURNAME5', N'28', N'SGL', CAST(N'2020-12-22T00:00:00.000' AS DateTime), N'LIVE', N'Single', N'249716717')

-- INSERT omang.OMANG_CITIZEN (DECEASED_DTE, FIRST_NME, BIRTH_DTE_UNKNOWN, DISTRICT_NME, OCCUPATION_DESCR, BIRTH_PLACE_NME, CHANGE_DTE, DISTRICT_CDE, SEX, SPOUSE_NME, CITIZEN_STATUS_CDE, DEATH_CERT_NO, BIRTH_DTE, DECEASED_DTE_UNKNOWN, CITIZEN_STATUS_DTE, SURNME, OCCUPATION_CDE, MARITAL_STATUS_CDE, EXPIRY_DTE, PERSON_STATUS, MARITAL_STATUS_DESCR, ID_NO) VALUES (NULL, N'IPONENG', N'N', N'NORTH-EAST', N'NOT IN THE LABOUR FORCE (STUDENT)', N'FRANCISTOWN', CAST(N'2012-10-05T12:44:34.000' AS DateTime), N'19', N'M', NULL, N'CITZ', NULL, CAST(N'1995-01-29T00:00:00.000' AS DateTime), NULL, CAST(N'2012-10-05T12:44:34.000' AS DateTime), N'SURNAME2', N'28', N'SGL', CAST(N'2022-10-04T00:00:00.000' AS DateTime), N'LIVE', N'Single', N'255715019')

-- INSERT omang.OMANG_CITIZEN (DECEASED_DTE, FIRST_NME, BIRTH_DTE_UNKNOWN, DISTRICT_NME, OCCUPATION_DESCR, BIRTH_PLACE_NME, CHANGE_DTE, DISTRICT_CDE, SEX, SPOUSE_NME, CITIZEN_STATUS_CDE, DEATH_CERT_NO, BIRTH_DTE, DECEASED_DTE_UNKNOWN, CITIZEN_STATUS_DTE, SURNME, OCCUPATION_CDE, MARITAL_STATUS_CDE, EXPIRY_DTE, PERSON_STATUS, MARITAL_STATUS_DESCR, ID_NO) VALUES (NULL, N'CAROLINE', N'N', N'FRANCISTOWN', N'NOT IN THE LABOUR FORCE (STUDENT)', N'FRANCISTOWN', CAST(N'2017-01-13T11:33:23.000' AS DateTime), N'02', N'F', NULL, N'CITZ', NULL, CAST(N'1987-01-13T00:00:00.000' AS DateTime), NULL, CAST(N'2017-01-13T11:33:23.000' AS DateTime), N'SURNAME10', N'28', N'SGL', CAST(N'2027-01-10T00:00:00.000' AS DateTime), N'LIVE', N'Single', N'258628219')

-- INSERT omang.OMANG_CITIZEN (DECEASED_DTE, FIRST_NME, BIRTH_DTE_UNKNOWN, DISTRICT_NME, OCCUPATION_DESCR, BIRTH_PLACE_NME, CHANGE_DTE, DISTRICT_CDE, SEX, SPOUSE_NME, CITIZEN_STATUS_CDE, DEATH_CERT_NO, BIRTH_DTE, DECEASED_DTE_UNKNOWN, CITIZEN_STATUS_DTE, SURNME, OCCUPATION_CDE, MARITAL_STATUS_CDE, EXPIRY_DTE, PERSON_STATUS, MARITAL_STATUS_DESCR, ID_NO) VALUES (NULL, N'JAMES', N'N', N'NORTH-EAST', N'NOT IN THE LABOUR FORCE (STUDENT)', N'FRANCISTOWN', CAST(N'2011-02-17T18:14:15.000' AS DateTime), N'19', N'F', NULL, N'CITZ', NULL, CAST(N'1993-01-21T00:00:00.000' AS DateTime), NULL, CAST(N'2011-02-17T18:14:15.000' AS DateTime), N'SURNAME4', N'28', N'SGL', CAST(N'2021-02-16T00:00:00.000' AS DateTime), N'LIVE', N'Single', N'259573715')

-- INSERT omang.OMANG_CITIZEN (DECEASED_DTE, FIRST_NME, BIRTH_DTE_UNKNOWN, DISTRICT_NME, OCCUPATION_DESCR, BIRTH_PLACE_NME, CHANGE_DTE, DISTRICT_CDE, SEX, SPOUSE_NME, CITIZEN_STATUS_CDE, DEATH_CERT_NO, BIRTH_DTE, DECEASED_DTE_UNKNOWN, CITIZEN_STATUS_DTE, SURNME, OCCUPATION_CDE, MARITAL_STATUS_CDE, EXPIRY_DTE, PERSON_STATUS, MARITAL_STATUS_DESCR, ID_NO) VALUES (NULL, N'OLORATO', N'N', N'CENTRAL-SEROWE', N'BOOK-KEEPERS, CASHIERS AND RELATED WORKERS', N'FRANCISTOWN', CAST(N'2016-04-26T15:00:38.000' AS DateTime), N'14', N'F', NULL, N'CITZ', NULL, CAST(N'1988-09-16T00:00:00.000' AS DateTime), NULL, CAST(N'2016-04-26T15:00:38.000' AS DateTime), N'SURNAME7', N'33', N'SGL', CAST(N'2026-04-25T00:00:00.000' AS DateTime), N'LIVE', N'Single', N'264520419')

-- INSERT omang.OMANG_CITIZEN (DECEASED_DTE, FIRST_NME, BIRTH_DTE_UNKNOWN, DISTRICT_NME, OCCUPATION_DESCR, BIRTH_PLACE_NME, CHANGE_DTE, DISTRICT_CDE, SEX, SPOUSE_NME, CITIZEN_STATUS_CDE, DEATH_CERT_NO, BIRTH_DTE, DECEASED_DTE_UNKNOWN, CITIZEN_STATUS_DTE, SURNME, OCCUPATION_CDE, MARITAL_STATUS_CDE, EXPIRY_DTE, PERSON_STATUS, MARITAL_STATUS_DESCR, ID_NO) VALUES (NULL, N'THATO', N'N', N'CENTRAL-TUTUME', N'TRANSPORT CONDUCTORS', N'FRANCISTOWN', CAST(N'2016-10-24T09:00:50.000' AS DateTime), N'18', N'M', NULL, N'CITZ', NULL, CAST(N'1988-03-14T00:00:00.000' AS DateTime), NULL, CAST(N'2016-10-24T09:00:50.000' AS DateTime), N'SURNAME8', N'36', N'SGL', CAST(N'2026-10-18T00:00:00.000' AS DateTime), N'LIVE', N'Single', N'272116516')

-- INSERT omang.OMANG_CITIZEN (DECEASED_DTE, FIRST_NME, BIRTH_DTE_UNKNOWN, DISTRICT_NME, OCCUPATION_DESCR, BIRTH_PLACE_NME, CHANGE_DTE, DISTRICT_CDE, SEX, SPOUSE_NME, CITIZEN_STATUS_CDE, DEATH_CERT_NO, BIRTH_DTE, DECEASED_DTE_UNKNOWN, CITIZEN_STATUS_DTE, SURNME, OCCUPATION_CDE, MARITAL_STATUS_CDE, EXPIRY_DTE, PERSON_STATUS, MARITAL_STATUS_DESCR, ID_NO) VALUES (NULL, N'MONTY', N'N', N'NORTH-EAST', N'NOT IN THE LABOUR FORCE (STUDENT)', N'FRANCISTOWN', CAST(N'2009-08-12T09:53:30.000' AS DateTime), N'19', N'M', NULL, N'CITZ', NULL, CAST(N'1990-07-13T00:00:00.000' AS DateTime), NULL, CAST(N'2009-08-12T09:53:30.000' AS DateTime), N'SURNAME6', N'28', N'SGL', CAST(N'2017-01-05T00:00:00.000' AS DateTime), N'LIVE', N'Single', N'286815515')

-- INSERT omang.OMANG_CITIZEN (DECEASED_DTE, FIRST_NME, BIRTH_DTE_UNKNOWN, DISTRICT_NME, OCCUPATION_DESCR, BIRTH_PLACE_NME, CHANGE_DTE, DISTRICT_CDE, SEX, SPOUSE_NME, CITIZEN_STATUS_CDE, DEATH_CERT_NO, BIRTH_DTE, DECEASED_DTE_UNKNOWN, CITIZEN_STATUS_DTE, SURNME, OCCUPATION_CDE, MARITAL_STATUS_CDE, EXPIRY_DTE, PERSON_STATUS, MARITAL_STATUS_DESCR, ID_NO) VALUES (NULL, N'KA', N'N', N'NORTH-EAST', N'WORKERS REPORTING UNIDENTIFIABLE OCCUPATIONS', N'FRANCISTOWN', CAST(N'2015-09-22T11:45:34.000' AS DateTime), N'19', N'F', NULL, N'CITZ', NULL, CAST(N'1988-09-11T00:00:00.000' AS DateTime), NULL, CAST(N'2015-09-22T11:45:34.000' AS DateTime), N'SURNAME9', N'25', N'SGL', CAST(N'2025-09-21T00:00:00.000' AS DateTime), N'LIVE', N'Single', N'373821113')

