---
- name: HAPI FHIR Server
  hosts: all
  remote_user: "{{ user }}"
  become: true
  tags: prep

  
  vars_prompt:
    - name: "user"
      prompt: "Please enter the username (with sudo)"
      private: no


  tasks:

  - name: Does hapi folder exist
    stat:
      path: $HOME/hapi-fhir-jpaserver-starter
    register: stat_result2


  - name: git clone repo (hapi jpa-server-starter v4.2.0)
    git:
      repo: 'https://github.com/hapifhir/hapi-fhir-jpaserver-starter.git'
      dest: /home/{{ user }}/hapi-fhir-jpaserver-starter
      clone: yes
      # note that this blows away any existing changes to files
      force: yes
      version: v4.2.0
    when: stat_result2.stat.exists == False


  - name: git pull if updated
    git:
      repo: 'https://github.com/hapifhir/hapi-fhir-jpaserver-starter.git'
      dest: /home/{{ user }}/hapi-fhir-jpaserver-starter
      update: yes



# default: fhir_version=R4      
# default: server_address=http://localhost:8080/hapi-fhir-jpaserver/fhir/

# add postgres to src/main/resources/hapi.properties

  - name: replace line(s) for postgres as datasource in hapi.properties
    lineinfile:
      path: /home/{{ user }}/hapi-fhir-jpaserver-starter/src/main/resources/hapi.properties
      regexp: '^datasource.driver='
      line: datasource.driver=org.postgresql.Driver

      
  - name: replace line(s) for postgres as datasource in hapi.properties
    lineinfile:
      path: /home/{{ user }}/hapi-fhir-jpaserver-starter/src/main/resources/hapi.properties
      regexp: '^datasource.url='
      # line: datasource.url=jdbc:postgresql://localhost:5432/hapi_dstu3
      line: datasource.url=jdbc:postgresql://localhost:5432/hapi


  - name: replace line(s) for postgres as datasource in hapi.properties
    lineinfile:
      path: /home/{{ user }}/hapi-fhir-jpaserver-starter/src/main/resources/hapi.properties
      regexp: '^hibernate.dialect='
      line: hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect


  - name: replace line(s) for postgres as datasource in hapi.properties
    lineinfile:
      path: /home/{{ user }}/hapi-fhir-jpaserver-starter/src/main/resources/hapi.properties
      regexp: '^datasource.username='
      line: datasource.username=hapi


# todo: need to sub in md5 hashed pwd 
  - name: replace line(s) for postgres as datasource in hapi.properties
    lineinfile:
      path: /home/{{ user }}/hapi-fhir-jpaserver-starter/src/main/resources/hapi.properties
      regexp: '^datasource.password='
      line: datasource.password=hapi
      

# builds /home/opencr/hapi-fhir-jpaserver-starter/target/hapi-fhir-jpaserver.war
# not necessary for mvn jetty runs but would be with tomcat or other approach
# must use -DskipTests as integration tests use builtin derby server not postgres
  - name: maven --no-transfer-progress --batch-mode package
    shell: /opt/apache-maven-3.6.3/bin/mvn package -DskipTests
    args:
      chdir: /home/{{ user }}/hapi-fhir-jpaserver-starter
    environment:
      MAVEN_OPTS: -Xmx1024m


# move package into tomcat/webapps
  - name: move war file to /opt/tomcat/webapps
    shell: cp hapi-fhir-jpaserver.war /opt/tomcat/webapps/
    args:
      chdir: /home/{{ user }}/hapi-fhir-jpaserver-starter/target/

# kick tomcat
  - name: kick tomcat
    service: 
      name: tomcat.service
      state: restarted
      enabled: yes
