---
- name: Preparation
  hosts: all
  remote_user: "{{ user }}"
  become: true
  tags: prep

  vars_prompt:
    - name: "user"
      prompt: "Please enter the username (with sudo)"
      private: no

  tasks:

  - name: Ensure git
    yum:
      name: git
      state: present


  - name: install enterprise packages for enterprise linux
    yum: 
      name: epel-release
      state: present


# node and npm
  - name: Download nodesource script for node v10
    get_url:
      url: https://rpm.nodesource.com/setup_10.x
      dest: $HOME/nodesource.sh
      mode: 0644
      # overwrite
      force: yes


  - name: Install nodesource for node 10
    command: bash $HOME/nodesource.sh


  - name: install nodejs packages
    yum: 
      name: nodejs
      state: present


  - name: Ensure npm is latest
    npm: 
      name: npm
      state: present
      global: yes


  - name: Ensure native tools for native builds
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - gcc-c++
      - make


# python psycopg2 for ansible to manage postgres
  - name: Ensure python-psycopg2 for ansible to manage postgres
    yum:
      name: python-psycopg2
      state: present


# java

  - name: Ensure java
    yum:
      name: java-1.8.0-openjdk-devel
      state: present

# tomcat
  # - name: Download Tomcat
  #   get_url: 
  #     url: https://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.27/bin/apache-tomcat-9.0.27.tar.gz
  #     dest: /opt/apache-tomcat-9.0.27.tar.gz


  # - name: Extract archive
  #   command: /bin/tar xvf /opt/apache-tomcat-9.0.27.tar.gz -C /opt/ 
  #   args:
  #     creates: /opt/apache-tomcat-7.0.61
  #     chdir: /usr/share /bin/tar xvf /opt/apache-tomcat-9.0.27.tar.gz -C /opt/ creates=/opt/apache-tomcat-9.0.27

    
  # - name: Symlink install directory
  #   file: 
  #     src: /opt/apache-tomcat-9.0.27 
  #     path: /usr/share/tomcat
  #     state: link


# this works but using another openjdk for now.
  # - name: Add repository for AdoptOpenJDK
  #   yum_repository:
  #     name: AdoptOpenJDK
  #     description: AdoptOpenJDK
  #     baseurl: http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/centos/7/x86_64/
  #     gpgcheck: yes
  #     gpgkey: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
  #     enabled: yes


  # - name: install adoptopenjdk packages
  #   yum: 
  #     name: adoptopenjdk-8-openj9
  #     state: present


# maven

# yum version of maven is too out of date for hapi, need to upgrade
  # - name: Ensure maven for java builds
  #   yum:
  #     name: maven
  #     state: present

  - name: Download Apache Maven 
    get_url: 
      url: https://www-us.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      dest: /tmp/apache-maven-3.6.3-bin.tar.gz

  - name: Untar Maven 
    shell: 
      chdir: /tmp 
      creates: /opt/apache-maven-3.6.3
      cmd: tar -zxf apache-maven-3.6.3-bin.tar.gz -C /opt

# will have to call maven by its abs path: /opt/apache-maven-3.6.3/bin/mvn

# not upgrading env
  # - name: Update path for maven use
  #   shell: export PATH=/opt/apache-maven-3.6.3/bin:$PATH


# enable cpu and memory accounting by systemd
  - name: Ensure memory accounting for systemd
    replace:
      path: /etc/systemd/system.conf
      regexp: '#DefaultMemoryAccounting=no'
      replace: 'DefaultMemoryAccounting=yes'
      backup: no

  - name: Ensure cpu accounting for systemd
    replace:
      path: /etc/systemd/system.conf
      regexp: '#DefaultCPUAccounting=no'
      replace: 'DefaultCPUAccounting=yes'
      backup: no
